version: "3"

services:
    zetted-api:
        image: zetted-api
        build:
            context: .
            dockerfile: ./Dockerfile
        environment:
            NODE_ENV: production
        ports:
            - 3001:80
